name: Build and Attach plugin zip on release

on:
  release:
    types: [published]

jobs:
  build-zip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create ZIP archive
        run: |
          cd travely-widget
          zip -r ../travely-widget-${{ github.event.release.tag_name }}.zip ./*
          cd ..

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: travely-widget-${{ github.event.release.tag_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}